#!/bin/bash
./pdallbuild && \
    rsync -avz *.html *.css linode:/home/eric/www/www.arinehart.com/ && \
    rsync -arvz images/ linode:/home/eric/www/www.arinehart.com/images/ && \
    rsync -arvz UsafImages/ linode:/home/eric/www/www.arinehart.com/UsafImages/
